### ISSUE TITLE
Get entries via parent

### ISSUE THREAD

**Issue by rehmatworks** [faustbrian/Laravel-Categories#30]
I created a hierarchy of categories where there are two main categories and several sub-categories belonging to them. While attaching a sub-category to a model, is it necessary to attach the main category as well or we can access the entries via the main category without attaching it?

Here is how I created the categories:
```php
$node = Category::create([
    'name' => 'Foo',
    'children' => [
        [
            'name' => 'Bar'
        ],
    ],
]);
```

And here is how Attached the category to post model:
```php
$cat = Category::where('name', 'Bar')->get()->first();
$post->categorize($cat);

```

This works fine when I retrieve via the sub-category that I used:
```
$cat = Category::where('name', 'Bar')->get()->first();
$posts = $cat->entries(Post::class)->get();
```

This doesn't work:
```
$cat = Category::where('name', 'Foo')->get()->first();
$posts = $cat->entries(Post::class)->get();
```
Any help would be highly appreciated.

**Comment by faustbrian** [comment]
Take a look at https://github.com/lazychaser/laravel-nestedset to get a better idea of how the nesting works, this package is used to handle all of that.
